# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(398, 293)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(50, -1, 50, -1)
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_user = QtWidgets.QLabel(Form)
        self.label_user.setObjectName("label_user")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_user)
        self.lineEdit_user = QtWidgets.QLineEdit(Form)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_user)
        self.label_pw = QtWidgets.QLabel(Form)
        self.label_pw.setObjectName("label_pw")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_pw)
        self.lineEdit_pw = QtWidgets.QLineEdit(Form)
        self.lineEdit_pw.setObjectName("lineEdit_pw")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pw)
        self.label_select_user_type = QtWidgets.QLabel(Form)
        self.label_select_user_type.setObjectName("label_select_user_type")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_select_user_type)
        self.comboBox_user_type = QtWidgets.QComboBox(Form)
        self.comboBox_user_type.setObjectName("comboBox_user_type")
        self.comboBox_user_type.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_user_type)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(60, -1, 60, 30)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_close = QtWidgets.QPushButton(Form)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.pushButton_login = QtWidgets.QPushButton(Form)
        self.pushButton_login.setObjectName("pushButton_login")
        self.horizontalLayout.addWidget(self.pushButton_login)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "用户登录"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">图书管理系统</p></body></html>"))
        self.label_user.setText(_translate("Form", "<html><head/><body><p align=\"right\">账号：</p></body></html>"))
        self.label_pw.setText(_translate("Form", "<html><head/><body><p align=\"right\">密码：</p></body></html>"))
        self.label_select_user_type.setText(_translate("Form", "登录类型选择："))
        self.comboBox_user_type.setItemText(0, _translate("Form", "管理员"))
        self.pushButton_close.setText(_translate("Form", "关闭"))
        self.pushButton_login.setText(_translate("Form", "登录"))
